name: Deploy para VPS v1as

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Atualizar código na VPS
        uses: appleboy/ssh-action@master
        with:
          host: 20.226.72.133
          username: tsilva
          password: N78mN4ykxHuskgx
          script: |
            cd /home/tsilva/frontend/SOFMARC-PROJETO_PDF_NEW_FRONT
            git pull origin dev
            #!/bin/bash
            npm run dev