name: Deploy para VPS v1as

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do reposit칩rio
        uses: actions/checkout@v2

      - name: Atualizar c칩digo na VPS
        uses: appleboy/ssh-action@master
        with:
          host: 20.226.72.133
          username: tsilva
          password: N78mN4ykxHuskgx
          script: |
            cd /home/tsilva/frontend/PROJETO_PDF_NEW_FRONT
            git pull origin master
            # Outros comandos necess치rios para atualizar o c칩digo na VPS
